### ISSUE TITLE
Is it appliable for analysing Bisulfite sequencing data?

### ISSUE THREAD

**Issue by sixone11** [jsh58/DMRfinder#10]
I try to use DMRfinder to analyse RRBS. I don't know if it is reasonable

**Comment by jsh58** [comment]
Thanks for the question.  Yes, DMRfinder is definitely a reasonable choice for analyzing RRBS data.  The [publication](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-017-1909-0) has some discussion of targeted sequencing approaches, for which DMRfinder is quite suitable.

**Comment by sixone11** [comment]
Thank you very much.It is really a good software!
