### ISSUE TITLE
Can I use customized region for finding significant DMR?

### ISSUE THREAD

**Issue by Honchkrow** [jsh58/DMRfinder#11]
Hello,
    I am interested in using your tool for finding significant CpG island between case and control. Can I use customized region for finding significant DMR? I mean changing combined.csv to customized region file like CpG island. If it is possible, what's the format (which column combined.csv needs to contain) should I create.
    Thanks for your help!
Honchkrow

**Comment by jsh58** [comment]
Thanks for the question.  Yes, you can filter your csv file before running `findDMRs.r`.  To select only regions overlapping a reference, I would recommend a tool such as [bedtools](https://bedtools.readthedocs.io/en/latest/content/tools/intersect.html).

The format of the input file for `findDMRs.r` is given under the description of the `-i <input>` argument [here](https://github.com/jsh58/DMRfinder#test).

**Comment by Honchkrow** [comment]
Thanks for your reply.
