### ISSUE TITLE
Multiple Errors with dispersion.shrinkage.BSseq

### ISSUE THREAD

**Issue by npatel22526** [jsh58/DMRfinder#12]
Hello, 
I was trying to run the DMRfinder.R script the way it's described in Readme , however, getting below error. It seems they both coming from a DSS utility 

Error 1 : I try fixing this by adding variable ncores =1

Comparing group "Control" to group "Disease"
  Estimating dispersion for each CpG site, this will take a while ...
Error in est.dispersion.BSseq(cbind(x1, x2), cbind(n1, n2), cbind(estprob1,  :
  object 'ncores' not found
Calls: DMLtest ... est.dispersion.BSseq -> dispersion.shrinkage.BSseq -> bpworkers
Execution halted

Error2 : 
Comparing group "Control" to group "Disease"
  Estimating dispersion for each CpG site, this will take a while ...
Error in (function (classes, fdef, mtable)  :
  unable to find an inherited method for function ‘bpworkers’ for signature ‘"numeric"’
Calls: DMLtest ... dispersion.shrinkage.BSseq -> bpworkers -> <Anonymous>
Execution halted

Thanks, 
Nick

**Comment by jsh58** [comment]
Nick,

Thanks for the question.  This may be an issue with DSS.  Are you using version 2.14.0?  That is the version I tested on, and I did not encounter such an error.

John Gaspar

**Comment by npatel22526** [comment]
Hello John,
Thanks, Yes, replacing current DSS (2.34.0)  with DSS 2.14.0 solved the problem. 

Best, 
Nick
