### ISSUE TITLE
not working on Bismark run with bowtie --local

### ISSUE THREAD

**Issue by Cori-JHU** [jsh58/DMRfinder#17]
Hi, 

is there any option to run DMRFinder after running Bismark with bowtie2 --local option ?
extract_CpG_data.py crashes because it does not expect CIGAR string to have a "S".

Thank you !

**Comment by jsh58** [comment]
Thanks for the question.  No, `extract_CpG_data.py` understands only the CIGAR ops `M`, `D`, and `I`.  Soft-clipped alignments are not allowed.

**Comment by Cori-JHU** [comment]
OK, thanks for confirming.
