### ISSUE TITLE
What is the issue with bismark >0.15.0

### ISSUE THREAD

**Issue by greatfireball** [jsh58/DMRfinder#4]
In your user guide, you suggest the usage of bismark 0.15.0 due to an issue introduced in version 0.16.0 and still persisting in 0.18.

Can you link the issue or describe the flaw? This would allow checking for that issue and maybe upgrading to a newer version of bismark.

Thanks in advance!

**Comment by jsh58** [comment]
@greatfireball 
The issue is described [here](https://github.com/FelixKrueger/Bismark/issues/56) and [here](https://github.com/FelixKrueger/Bismark/pull/58).

**Comment by greatfireball** [comment]
Thx for your answer!
