### ISSUE TITLE
How can I provide pair information to do pairwise differential methylation analysis?

### ISSUE THREAD

**Issue by bishwaG** [jsh58/DMRfinder#5]
Hi,

I have RRBS data with twin pair study design. How can I provide pair information to DMRfinder to perform pairwise differential methylation analysis?

**Comment by jsh58** [comment]
Thanks for the question.  The sample groups to be tested for differential methylation are specified in the call to `findDMRs.r`.  For more details please consult the [User Guide](https://github.com/jsh58/DMRfinder/blob/master/UserGuide.pdf) or the just-updated README, in particular the [Quick start](https://github.com/jsh58/DMRfinder#quick) and [Testing regions](https://github.com/jsh58/DMRfinder#test) sections.

John Gaspar

**Comment by bishwaG** [comment]
Thank you @jsh58

**Comment by bishwaG** [comment]
Is it possible to adjust covariates in DMRfinder?

**Comment by jsh58** [comment]
I do not think so, but you can check the [DSS](https://bioconductor.org/packages/release/bioc/html/DSS.html) documentation to see what is possible there.

**Comment by bishwaG** [comment]
Hi @jsh58 
It looks like it is possible to adjust covariates in DSS.
