### ISSUE TITLE
Manual clustering info

### ISSUE THREAD

**Issue by Lux91** [jsh58/DMRfinder#6]
Hi, I am trying to create the clustered regions manually because I have a bed file with predefined regions but I also want to use your R script to find DMRs. My only question is: How do I manually calculate the "CpG" field of the combined regions?
Thanks

**Comment by jsh58** [comment]
Thanks for the question.  To manually calculate the `CpG` field, you would need to query the genome sequence for `CG` dinucleotides in the regions of interest.  But, if you are not actually interested in using this field for downstream purposes, you could probably get away with just setting a large value for the field (say, 10) and not using the `-c` parameter of `findDMRs.r`.

**Comment by Lux91** [comment]
Thank you very much for your help :)
