### ISSUE TITLE
Error in `[<-.data.frame`(`*tmp*`, , !col %in% dss & !substr(col, 1, nchar(col) -  :    replacement has 0 items, need 10 Calls: [<- -> [<-.data.frame Execution halted

### ISSUE THREAD

**Issue by kkk0-000** [jsh58/DMRfinder#8]
I used DMRfinder to correct DMRs in high sequence methylation data.
I used the test.csv file as example: 

![_20181023162242](https://user-images.githubusercontent.com/7838505/47346559-059d1880-d6e0-11e8-8591-0fa73f4714c5.png)

The error was:

![_20181023162340](https://user-images.githubusercontent.com/7838505/47346610-21a0ba00-d6e0-11e8-947c-c9e6bedf2b5e.png)

I ran command on ubuntu server,

![_20181023162416](https://user-images.githubusercontent.com/7838505/47346671-3f6e1f00-d6e0-11e8-920a-8416aacd56d0.png)

Now I don't know how to solve the error.

**Comment by jsh58** [comment]
@khl0798 

I cannot reproduce that error on my computer, which has `R v3.5.0` and `DSS v2.28.0` installed.  I recommend that you check that your `test.csv` file does not have any extra blank lines or tabs, and that your version of `DSS` is up to date.

**Comment by kkk0-000** [comment]
> @khl0798
> 
> I cannot reproduce that error on my computer, which has `R v3.5.0` and `DSS v2.28.0` installed. I recommend that you check that your `test.csv` file does not have any extra blank lines or tabs, and that your version of `DSS` is up to date.


Many thanks. I changed version of ```R v3.2.3``` to ```R v3.4.4``` and  reinstalled ```DSS  ```. There is no more error. @jsh58
